import './globals.css'

export const metadata = {
  title: 'My Website',
  description: 'Generated by me'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  )
}
