import { ReactNode } from 'react'
import './globals.css'

export const metadata = {
  title: 'My Website',
  description: 'Generated by me'
}

interface Props {
  children: ReactNode
  team: ReactNode
  member: ReactNode
}

export default function RootLayout(props: Props) {
  return (
    <html lang='en'>
      <body>
        {props.children}
        {props.member}
        {props.team}
      </body>
    </html>
  )
}
