// import main from './src/1'
// import main from './src/2'
// import main from './src/3'
// import main from './src/4'
// import main from './src/5'
// import main from './src/6'
// import main from './src/7'
// import main from './src/8'
// import main from './src/9'
// import main from './src/10'
// import main from './src/11'
// import main from './src/12'
// import main from './src/13'
// import main from './src/haunted-house'
// import main from './src/14'
// import main from './src/galaxy'
// import main from './src/15'
import main from './src/16-physics'

import './index.css'

main()
